### ISSUE TITLE
npm ci

### ISSUE THREAD

**Issue by jalallinux** [imbudhiraja/express-boilerplate#10]
when run this command: npm ci
i get this error 
![Screen Shot 1399-07-03 at 20 58 30](https://user-images.githubusercontent.com/37062636/94179035-ce75aa00-fea8-11ea-92a6-0c80bc7a61dc.png)

**Comment by imbudhiraja** [comment]
This is because `eslint-config-imbudhiraja@1.1.0` is unpublished from npm registry. You should try `npm i -D eslint-config-imbudhiraja@latest` it resolve the issue. I'll fix this soon

**Comment by codemarka** [comment]
soon should be quick tbh, because this project is not valid atm

**Comment by imbudhiraja** [comment]
@jalallinux @codemarka Issue has been fixed.
